### ISSUE TITLE
@ mentions in notifications display the Session ID instead of username

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/session-android#102]
**Describe the bug**
@ mentions in notifications display the Session ID instead of username. 

**To reproduce**
Get a notification with a @ mention in it. 

**Screenshots or logs**
![Screenshot_20200218-030434](https://user-images.githubusercontent.com/29006257/74700587-e93dbd00-51fb-11ea-8f39-d0dc1dbf555c.png)
![Screenshot_20200218-030453](https://user-images.githubusercontent.com/29006257/74700594-f195f800-51fb-11ea-993b-48e67db9d606.png)

**Smartphone (please complete the following information):**
 - Device: Xperia xz2 premium 
 - OS:  Android 10
 - Version of Session: 1.0.2

**Comment by gmbnt** [comment]
This has been fixed.

**Comment by Brice-W** [comment]
I have that issue on Desktop, iOS and Android
