### ISSUE TITLE
Message highlight function delay

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/session-android#103]
**Describe the bug**
When holding down on a message to highlight it green the phone vibrates to let you know the message has been selected but it does not highlight the message green until you scroll up or down. Message should highlight straight away instead of after scrolling. 

**To reproduce**
Hold down on a message until phone vibrates. Message will not highlight until srolling. 

**Smartphone (please complete the following information):**
 - Device: Xperia xz2 premium 
 - OS: Android 10
 - Version of Session: 1.0.2

**Comment by Lucifer1903** [comment]
Also holding down on a selected message should deselect the message. Current there is no way to deselect the message except for going back to the main page.

**Comment by KeeJef** [comment]
This seems to be fixed in the current release for me

**Comment by Brice-W** [comment]
Message selection issues have been fixed
