### ISSUE TITLE
Reduce the number of permissions

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [loki-project/session-android#107]
Hi there,

I used Exodus Privacy to have a report on Trackers and permissions of session.
https://reports.exodus-privacy.eu.org/fr/reports/network.loki.messenger/latest/

![image](https://user-images.githubusercontent.com/19731340/74921138-a03d6280-53cd-11ea-9964-ccd3487ebc63.png)

0 trackers : Great !

But 52 permissions, some of them seems strange to me :

![image](https://user-images.githubusercontent.com/19731340/74921319-ebf00c00-53cd-11ea-9424-03962cfe4527.png)

![image](https://user-images.githubusercontent.com/19731340/74921363-f7433780-53cd-11ea-90ee-2c56127d8eee.png)

![image](https://user-images.githubusercontent.com/19731340/74921423-0924da80-53ce-11ea-822b-2081e6180191.png)

![image](https://user-images.githubusercontent.com/19731340/74921445-14780600-53ce-11ea-995b-3877a931590b.png)

Can you explain the use of those please ?

**Comment by cypherpunk1984** [comment]
You people claim to develpe a privacy messenger, but actually the app requests almost the same amount of permissions as Whatsapp and Facebook. It asks for the ID permission, the phone state permission, the network info permission. Why do you claim we don't need a phone number to use the app but in reality you are getting our phone numbers from the permission requests? You claim that you don't need to know our IP address, but the app actually makes requests for all that information? Why would I suggest this app over Whatsapp? it still the same garbage privacy-wise but worst feature-wise. I bet F-droid wouldn't even allow your app in their repositories.

**Comment by KeeJef** [comment]
These permissions are left over from Signal, since we are forked from Signal, we don't actually use any of these permissions in the app, but they are still being detected by the code analyser. 

We have removed all unnecessary permissions in these two pull requests a couple of days ago https://github.com/loki-project/session-android/pull/120 , https://github.com/loki-project/session-android/pull/117

These changes are now merged in and we will be making a release in the next few days so they static analysis does not trigger. We don't need or collect any of these details

**Comment by cypherpunk1984** [comment]
> These permissions are left over from Signal, since we are forked from Signal, we don't actually use any of these permissions in the app, but they are still being detected by the code analyser.
> 
> We have removed all unnecessary permissions in these two pull requests a couple of days ago #120 , #117
> 
> These changes are now merged in and we will be making a release in the next few days so they static analysis does not trigger. We don't need or collect any of these details

I just analyzed the app with XPrivacyLua and you are right, the app is not using any of those permissions, it is not even trying to request any of that information. Thanks for the clarification.
I'm glad you are removing them soon, because it leads to confusion and misinterpretation.

**Comment by KeeJef** [comment]
We have updated the application and removed unused code that was causing GSF and Permissions static analyzers to trigger, https://reports.exodus-privacy.eu.org/en/reports/network.loki.messenger/latest/
