### ISSUE TITLE
Clicking "Session is unlocked" gives Signal-like UI

### ISSUE THREAD

**Issue by MuntashirAkon** [loki-project/session-android#108]
After enabling Screen Lock, a persistent notification (similar to Signal) appears which says "Session is unlocked". On clicking this notification, Signal-like UI appears instead of the Session's UI. Some settings in this UI is also non-clickable.

**To reproduce**
1. Settings > Privacy > Screen Lock = true
2. Click on the "Session is unlocked" in the notification
3. Signal-like UI

**Smartphone:**
 - Device: Not relevant
 - OS: Android 10
 - Version of Loki Messenger: 1.0.2

**Comment by nielsandriesse** [comment]
This should now be fixed :)
