### ISSUE TITLE
google dependances 

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [loki-project/session-android#118]
hi dependances google bad idea for you,r project because google bad for freedoom 

please remove dependances google 

you can use own websocket for notification (ex tutanota, fedilab)

com.google.firebase.iid.FirebaseInstanceIdService
com.google.firebase.components.ComponentDiscoveryService

com.google.android.gms.auth.api.signin.RevocationBoundService
com.google.firebase.messaging.FirebaseMessagingService

**Comment by Mikunj** [comment]
This should be fixed now. Let me know if there are more :)
