### ISSUE TITLE
Can't link Linux device (secondary) to Android (primary)

### ISSUE THREAD

**Issue by alexandrestein** [loki-project/session-android#119]
**Describe the bug**
Devices do not link.

**To Reproduce**
My primary device is an Android (1.0.3) and the secondary is a Linux desktop (1.0.2).
After inserting the Android Session ID I got a message I posted as an image. It tells me "Here is your secret".
But I can't do anything after this and nothing happens on the Android.

**Screenshots or Logs**
![Capture d’écran du 2020-02-25 11-20-40](https://user-images.githubusercontent.com/5431025/75238227-ee34da80-57c0-11ea-89db-306e0570aebb.png)

**Other information (please complete the following information):**

* Device: Dell Latitude and Motorola X4
* OS: Linux Manjaro kernel 5.5.2 and Android 9
* Session Version or Git commit hash: 1.0.2 for the Linux and 1.0.3 (update this morning) for Android.

I noticed that the other way around seems to work.

**Comment by nielsandriesse** [comment]
This should now be fixed :)
