### ISSUE TITLE
Updates keep showing up

### ISSUE THREAD

**Issue by madduck** [loki-project/session-android#121]
Whenever I delete the thread about updates from Loki about Session, a few hours later it reappears with the same (old) message, and I get a notification about it. That's pretty annoying.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Same here, the messages reaper almost instantly to me, though, I would really love I could choose to have that or not.

**Comment by nielsandriesse** [comment]
This has been fixed
