### ISSUE TITLE
Seed phrase does not create the same account across platforms

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [loki-project/session-android#122]
**Describe the bug**
I create an account on Android, copy the seed phrase and enter it in my desktop client. The account created on my desktop does not match that on my android and vice versa.

**To reproduce**
1. create an account on android
2. copy the seed phrase and enter it in your desktop client
3. see how the accounts are different

**Screenshots or logs**
let me know if you need it

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8, random laptop
 - OS: Android Pie, Ubuntu 19
 - Version of Loki Messenger or latest commit hash: 1.0.4 

**Additional context**
n/a

**Comment by Mikunj** [comment]
Huh interesting, i thought i had fixed this issue. I will look into this.

**Comment by Engineer-of-Stuff** [comment]
awesome, thanks for the quick reply

**Comment by gmbnt** [comment]
I believe this has been fixed. Closing the issue.
