### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by kojid0** [loki-project/session-android#128]
It would be nice to have a light mode for Session. I really don't like the dark colors.

**Comment by 1337n0m4d** [comment]
I agree, the overall look is much too black. Colours matter to people and a pure black UI has a negative feeling or connotation. Nobody uses black for a messenger precisely because of this negative down feeling.

There needs to be a light theme for people with a changeable message background.

**Comment by 1337n0m4d** [comment]
This should be a feature request

**Comment by Skelaton4** [comment]
There is a "Light Mode" being actively worked on. 

See: https://github.com/loki-project/session-ios/pull/107

I am assuming it will be on both Android and IOS

**Comment by KeeJef** [comment]
this has been added
