### ISSUE TITLE
Text cut off when sent with photo

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/session-android#129]
**Describe the bug**
Attaching photos and writing text to go along with it causes the end of the text to be cut off. 

**To reproduce**
Attach a photo and write a average size message. Send the message and photo together. Only the first few words will display. 

**Screenshots or logs**
![Screenshot_20200305-064609](https://user-images.githubusercontent.com/29006257/75955084-1d2c0a00-5ead-11ea-8c3a-620f826ea7b8.png)

**Smartphone (please complete the following information):**
 - Device: Xperia xz2 premium & Huawei P30 pro
 - OS: Android 10
 - Version of Session: 1.0.5

**Comment by Brice-W** [comment]
Same issue as [#233](https://github.com/loki-project/session-android/issues/233)

**Comment by KeeJef** [comment]
This is fixed in the latest release
