### ISSUE TITLE
Bug: Message order inverted

### ISSUE THREAD

**Issue by mrcnpp** [loki-project/session-android#130]
**Describe the bug**
Sometimes the replay of a message is showed before the initial message
Ex
user2:Good Thanks
user1:How are you today?

**To reproduce**
don't know how to reproduce

**Screenshots or logs**
![screen_loki](https://user-images.githubusercontent.com/8047343/76170112-281dbd80-617f-11ea-819c-d1a2ea72a421.jpg)
![screen_loki2](https://user-images.githubusercontent.com/8047343/76170113-28b65400-617f-11ea-85e9-e3a66d20f6ec.jpg)

**Smartphone (please complete the following information):**
 - Device: [One plus 5]
 - OS: [Android Oxigen OS 9.0.1]
 - Last version on the play store 1.0.6

**Additional context**

**Comment by Brice-W** [comment]
This should be fixed
