### ISSUE TITLE
Can't join some open groups

### ISSUE THREAD

**Issue by KeeJef** [loki-project/session-android#133]
Some groups, in particular loki.opensession.id wont properly join, other users have reported this happening with other groups. Essentially when you add the group the app will just move back to the conversations screen but the chat will never get added. 

There is no visibility to the user as to whether something has actually failed or not

**Comment by Mikunj** [comment]
I've investigated this as it looks like the app takes a long time verifying open group messages and thus it takes a very long time for open groups to show up after joining.

```
2020-03-18 12:01:19.284 9350-10906/network.loki.messenger W/Loki: Verifying signature for 58 messages
2020-03-18 12:02:05.457 9350-11304/network.loki.messenger W/Loki: Finished verifying signatures: 58
```
As you can see here, verifying 58 messages takes about a minute.
