### ISSUE TITLE
Can't link Android device (secondary) to Linux (primary)

### ISSUE THREAD

**Issue by androclus** [loki-project/session-android#142]
**Describe the bug**
Devices do not link

**To reproduce**
- My primary device is a Linux laptop and the secondary is an Android phone.
- I already have the Linux primary Session app installed and running and I have connected and chatted with a friend.
- Now I install the Android Session app, intending to make it a secondary linked device to the Linux laptop.
- On the Linux Session, I click on "Link New Device", and a QR screen comes up indicating it is waiting for a connection. (By the way, if I do this out of order (i.e., start the below Android connection first), the two will never even sync. But there is nothing in either app telling me to do it in this order. So I think there needs to be some text added in all places to say that the primary Session "Add Device" has to be started first.)
- At very first Android app opening screen, I do not create its own Session ID. Instead, since I want this to be linked to my Linux laptop, I click (on the Android screen) on 'Link to an existing account'.
- At the next Android screen (Link to your device), I insert my Linux laptop's Session ID (either via QR code, or by copying over the Session ID and pasting in)
- After inserting in the Android the Linux's Session ID (by either method), I do get a popup on the Linux box asking me to confirm that I want to pair to this (the Android) device, and giving me the three words, 'upcoming needed muffin', which are the same three that show up on the Android -- this is good, as they agree. I press yes, I want to pair this Linux Session with that Android device.
- The Linux Session next asks me for an alias for the secondary (Android) device, and I replace the default 'Unknown device' with 'phone' and submit.
- After that, I get nothing: The Linux pop-ups disappear and return to the empty Device Settings page saying 'No paired devices', and nothing else. No feedback.  Likewise, the Android screen hangs (with throbbing white orb) on 'Waiting for Authorization'.
- Nothing more happens on either device.

**Linux Screenshot**
![session-linux](https://user-images.githubusercontent.com/221629/76586512-4694f900-649e-11ea-93ce-a8c855387a20.png)

**Android Screenshot**
![session-android](https://user-images.githubusercontent.com/221629/76586537-53195180-649e-11ea-802d-ca01a05763a6.png)

**Android Log**
I cannot get the Android log, since I haven't yet signed in.

**Linux log**
[Linux log](https://debuglogs.org/d66440711a199c9a358b333e33b58ea6739447238249f556be267f94cc28c51d)

**Smartphone**
 - Device: ZTE ZMax Pro Z981
 - OS: Android 6.0.1  
 - Version of Session: 1.0.6 (from Google Play Store)

**Desktop**
- HP 17-by0053od, Intel Core i3 8th gen, 12GB RAM
- OS: OpenSUSE Tumbleweed 20200307, kernel 5.5.7-1-default x86_64
- Version of Session: 1.0.4 (session-messenger-desktop-linux-x86_64-1.0.4.AppImage)

**Additional context**
- Both connected at home behind my router. Android via wifi and my HP laptop by ethernet cable.
- Please let me know if there is any more info I can provide.

**Comment by Mikunj** [comment]
Thank you for the detailed report, this will make it easier to look for any issues :)

**Comment by androclus** [comment]
Interesting. I came back to my Linux session a couple of hours later, and now I see in the Device Settings window, 4 "devices" (which are all really my 1 Android device.

![session-linux2](https://user-images.githubusercontent.com/221629/76593027-4e5e9880-64b2-11ea-9bce-0a047897b084.png)

So maybe it was a "lag" issue of servers or something?

However, I still cannot get into my Android Session app because:

- a) there is no way for me to go back and use these older pairings: My Android app is still on the home screen (I had shut it down)

- b) The "Link New Device" button on the Linux app (as you see) is now inactivated. So I cannot create/pair a new device.

So I delete these 4 pairings, and after the 4th is deleted, the "Link New Device" button re-activates.

I try again. This time the Linux side confirms pairing -- this is different behavior, and an improvement. But the Android side still hangs on the "Waiting for Authorization" screen.  The 3 key words again match across the 2 devices.

**Linux log 2**
[Linux Log 2](https://debuglogs.org/553236e1f6cd847eb101dc9ca954e84925b470f5104d3529b479be7fbdd36b58)

Hope this helps.

**Comment by mmstick** [comment]
Same issue here with Android 10 (Google Pixel) attempting to authorize to a session created with Session Desktop 1.0.7 on Pop!_OS 20.04. The link device dialog disappears after the device is "linked", but the Android client continues to display "Waiting for authorization" indefinitely.

**Comment by nielsandriesse** [comment]
This should work more reliably now

**Comment by adojck** [comment]
Still have same issue, stuck at "Waiting for Authorization" screen.

Primary is Session v1.0.6 on Arch Linux
Secondary is latest Android version on Samsung Galaxy S10+

It shows that it is linked on desktop app, but says waiting for auth on the android phone

**Comment by Skelaton4** [comment]
The latest version  of the Desktop GUI is 1.0.9. Try that and see if it fixes your issues.
