### ISSUE TITLE
Difficult to see last 2 conversations on the main page

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/session-android#147]
**Describe the bug**
When you scroll to the bottom of the conversation lists the Last 2 are difficult to see. To fix this the list should be scroll past the plus button leaving an empty space the size of 2 conversion widths, this would allow the last conversation on the list to be just above the plus button. 

**To reproduce**
Have enough conversations to fill past the page. Scroll to the bottom and you will see that it is difficult to see the last 2 conversations. 

**Screenshots or logs**
![sketch-1584506831573](https://user-images.githubusercontent.com/29006257/76926455-52d0ea00-68d4-11ea-8ef1-744ad475aca8.png)

**Smartphone (please complete the following information):**
 - Device: Xperia xz2 premium 
 - OS: Android 10
 - Version of Session: 1.0.7

**Comment by gmbnt** [comment]
This has been fixed
