### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by Zerpyre** [loki-project/session-android#150]
**Describe the bug**
Build Fail error: cannot find symbol

**To reproduce**
Clone repository and build, try to create apk

**Screenshots or logs**
<a href="https://ibb.co/LpCTt67"><img src="https://i.ibb.co/0Jf0MZb/Captura.png" alt="Captura" border="0"></a>

**Smartphone (please complete the following information):**
 - Device: [null]
 - OS: [null]
 - Version of Loki Messenger or latest commit hash

**Additional context**
It also gave error in downloading kotlin-extension-plugin, but it was fixed in changing position of * kotlin-plugin * and * Kotlin-extension-plugin * bluid.gradle

**Comment by Mikunj** [comment]
You will need to do the following:
1. Clone `https://github.com/loki-project/session-android`.
2. Clone `https://github.com/loki-project/session-android-service`
3. navigate to session-android-service and run `./gradlew install`
4. Open session-android in android studio and wait for sync

After that just try build again, is this what you have already done?

**Comment by Zerpyre** [comment]
Yes, I did it again with your instructions but follow the same error, it also comes out
<a href="https://ibb.co/JcP9d46"><img src="https://i.ibb.co/vc8SBGy/Captura2.png" alt="Captura2" border="0"></a>

**Comment by Zerpyre** [comment]
Fix the second comment, I put in build.gradle kapt "the dagger plugin" and repositioned the kotlin plugin string, but I still get error compiling because it doesn't recognize optional symbol

**Comment by Zerpyre** [comment]
> 
> 
> You will need to do the following:
> 
>     1. Clone `https://github.com/loki-project/session-android`.
> 
>     2. Clone `https://github.com/loki-project/session-android-service`
> 
>     3. navigate to session-android-service and run `./gradlew install`
> 
>     4. Open session-android in android studio and wait for sync
> 
> 
> After that just try build again, is this what you have already done?

Yes, but the error is that it does not recognize the optional symbol and ends up giving an error without compiling

**Comment by nielsandriesse** [comment]
We've updated the build instructions and validated that they work. Please see: https://github.com/loki-project/session-android/blob/master/BUILDING.md .
