### ISSUE TITLE
Different interfaces depending on how I open the app

### ISSUE THREAD

**Issue by jeLee6gi** [loki-project/session-android#153]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I get different user interfaces when I open the app via
* app drawer or the recent apps
* the persistent "Session is unlocked Touch to open!" notification

The interface is different in the list of conversation and the settings menus. I think it is the same in a conversation.

### Steps to reproduce
Open the app via one of the ways described above

**Actual result:** The app shows different user interfaces
**Expected result:** It should show the same user interface

### Screenshots
I haven't looked into how I can get past the screenshot restriction ... I'll be happy to provide some if necessary

### Device info

**Device:** Samsung A51
**Android version:** 10
**Signal version:** 1.0.9

**Comment by gmbnt** [comment]
Good catch! Fixed in #154.
