### ISSUE TITLE
Session not accessing Contacts on Android

### ISSUE THREAD

**Issue by bertlebbert** [loki-project/session-android#157]
I just installed Sessions 10.0.1 on rooted Galaxy S7 running Android 8.0.0 and it seems unable to access the phone's Contacts. Not sure if this is a bug or I'm doing something wrong. (I am able to send and receive msgs to and from Session installed on PC).

No 'Contacts' icon displayed at top of page:
![NoIcon](https://user-images.githubusercontent.com/13893695/77682394-1ba5ad00-6f54-11ea-877f-facf4f48156d.jpg)

Attempt to share Session ID works with other apps Signal and Messenger, but not with Session.
![Error](https://user-images.githubusercontent.com/13893695/77682910-d8980980-6f54-11ea-8e25-147d0fac30e2.jpg)

There is no option to enable access to Contacts under App settings:
![Permissions](https://user-images.githubusercontent.com/13893695/77683265-5d832300-6f55-11ea-8a51-055e0f626233.jpg)

**Comment by EchedeyLR** [comment]
Same issue here

**Comment by bertlebbert** [comment]
I think I will close this, it's not really an issue... there is no reason for Session to access my contacts the way Signal does. It needs only to access Session recipients that I have explicitly added and successfully exchanged a "friend" request.

**Comment by nielsandriesse** [comment]
This behavior is intentional :)

**Comment by EchedeyLR** [comment]
Thank you for fixing the remaining unknown issue.
