### ISSUE TITLE
Remote service fails 

### ISSUE THREAD

**Issue by J-torres96** [loki-project/session-android#159]
**Describe the bug**
Following steps to make it remote fails

**To reproduce**
I apply the change in build.gradle and syc

**Screenshots or logs**
<a href="https://ibb.co/Vv5J2BK"><img src="https://i.ibb.co/LCHYnpG/Captura2.png" alt="Captura2" border="0"></a>

ERROR 

<a href="https://ibb.co/rktShTn"><img src="https://i.ibb.co/b13ZVqp/Captura.png" alt="Captura" border="0"></a>

**Additional context**
I don't have NDK installed, could it be the possible failure in this case?

**Comment by nielsandriesse** [comment]
Building should work if you follow the instructions outlined here: https://github.com/loki-project/session-android/blob/master/BUILDING.md
