### ISSUE TITLE
Sync not working Android/PC or Android/iPad

### ISSUE THREAD

**Issue by datgb** [loki-project/session-android#162]
Account first setup on Android. Won't sync at all with iPad. Device gets stuck on waiting for approval. 

When setup on PC can never get past the bad encrypted message. New secure session restore setup and doesn't do anything.

**Comment by eltacobaco** [comment]
I have the same issue. I got it running on my android device, and when I tried to sync with my PC after entering the session ID, it keeps loading.

**Comment by nielsandriesse** [comment]
This should now be fixed

**Comment by D4708** [comment]
The same issue, bad encrypted messages, conversation not synced between linked devices... 

**Sender desktop device info**
Android version: Ubuntu Linux 20.04
App version: v1.3.1

**Sender mobile device info**
Android version: 10
App version: 1.5.4 (995)

**Recipient mobile device info**
Android version: 9
App version: 1.5.4 (995)
