### ISSUE TITLE
@ Mentions: part of ID added to the message

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-android#164]
**Describe the bug**

In Android: in the text area when I select a member to mention in the @ list, it adds a portion of the ID after the name:
@member (…1234ef78)

**To reproduce**

On an Android device, type @ to mention a member and select a member in the list

**Screenshots or logs**

<img width="350" alt="Screen Shot 2020-04-07 at 10 14 09 am" src="https://user-images.githubusercontent.com/62363622/78619075-99a47500-78bf-11ea-8581-9c3105aac5b5.png">

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy S8]
 - OS: Android
 - Version of Loki Messenger or latest commit hash: 1.0.11

**Additional context**

**Comment by KeeJef** [comment]
This is the intended functionality as usernames are not unique, the content in brackets is a part of the Session ID of the user and can be used to differentiate between two users with the same username
