### ISSUE TITLE
Restarting Session while pairing creates a new session ID

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-android#172]
**Describe the bug**

Restarting Session while it is pairing creates a new session ID with no display name.

**To reproduce**

Open Session without any existing account or delete the existing account.
Click on ‘Link to an existing account’, enter an ID and press ‘Next’.
Close the Session app.
Reopen Session: it has created a new Session ID with no username.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Nexus 5
 - OS: Android 10.0
 - Version of Loki Messenger or latest commit hash:
Android: 2af186a8bf0e23c1a69c19047f9b9487f430aa47
Android service: 2421a7a9376a40a225ed68228753b2d44ef6a80f

**Additional context**

**Comment by KeeJef** [comment]
Closed due to multi device being removed
