### ISSUE TITLE
Message communication 1-way Failure

### ISSUE THREAD

**Issue by Skelaton4** [loki-project/session-android#177]
**Describe the bug**
My phone Galaxy S9+, Android 10, Session 1.1, can send messages to my partners mobile, her device Google Pixal 3a, Android 10, Session 1.1, cannot send any messages. Her device gets "message failed" but she gets mine.

Neither has multi devices connected.

**To reproduce**
Send message? 

**Screenshots or logs**
![Screenshot_20200419-230341_Session](https://user-images.githubusercontent.com/28955674/79710330-af884180-8292-11ea-8f69-87fab187d4e7.jpg)
![image000000](https://user-images.githubusercontent.com/28955674/79710331-af884180-8292-11ea-93cf-90e6498072d8.png)

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S9+/Google Pixal 3a
 - OS: Android 10 both
 - Version of Session 1.1 for both

**Additional context**

**Comment by KeeJef** [comment]
when you click on the send failed (tap for details) what does it say?

**Comment by HeinrichLong** [comment]
Having similar problem with S9+. The S9+ can receive messages from Session running on Windows desktop or Ubuntu desktop. It can't send messages, or send confirmation of friend request. When I "tap for details" all it says is, "Some issues need your attention" with a blue Resend button next to the text.

**Comment by Skelaton4** [comment]
Fixed with new 1.2
