### ISSUE TITLE
Google Firebase Analytics found in Session

### ISSUE THREAD

**Issue by ornyon** [loki-project/session-android#178]
Hi,

This is my very first post on Github, because someone on reddit recommanded me to report my findings, please kindly let me know if I should edit my post to make it clearer or if I'm in the wrong place. Also, I am not a native speaker, please forgive my mistakes.

**Description of the bug**
Bug : not exactly a bug but I tested Session with ClassyShark3xodus and it identified a Google Firebase Analytics tracker. I believe it is not in line with Session global philosophy.

I downloaded Session from Aurora Store yesterday so version is 1.1.0.495

**To reproduce**

1. Download ClassyShark3xodus from F-Droid
2. Download Session
3. Launch ClassyShark3xodus and look for Session in the apps list
4. Tap Session and check the results

**Screenshots or logs**

Here are 2 screens from classyShark3xodus

![Screenshot_20200421-092907_ClassyShark3xodus](https://user-images.githubusercontent.com/64065581/79841021-1737ad00-83b7-11ea-9667-1263e5ebab5d.png)

![Screenshot_20200421-092917_ClassyShark3xodus](https://user-images.githubusercontent.com/64065581/79841053-24549c00-83b7-11ea-878c-90dad97e254d.png)

**Smartphone (please complete the following information):**

 - Device: Xiaomi Pocophone F1
 - OS: LineageOS 17.1
 - Version of Session : 1.1.0.495

**Additional context**

None

**Comment by KeeJef** [comment]
We have included Google Firebase as of last patch 1.0.7, Users have an option when they use the application to either use Google Firebase for push notifications (more reliable) or Background polling(less reliable notifications, but more private). If the user chooses to use to use Background polling this Google Firebase code path is never followed. So users must opt into push notifications from Google which we feel is fine compromise.

**Comment by selurvedu** [comment]
Could you please consider making a build flavour which excluded those libraries completely? That would really ease the preparation for Session to be published in F-Droid
