### ISSUE TITLE
Request: Provide checksums and signature for each binary release

### ISSUE THREAD

**Issue by beantaco** [loki-project/session-android#179]
I've tried Session and it looks impressive, but release 1.1.0 doesn't come with any checksums or signature. Please provide these for all binaries so that there is some assurance downloads are good and GitHub or any other middle man is not messing with them.

**Comment by EchedeyLR** [comment]
Wtf, seems that they forgot to make it. I didnt take it in account until now.

**Comment by beantaco** [comment]
Session 1.2.0 has signed checksums.

The release process should be automated in such a way that nothing is released for end users without signed checksums.

**Comment by EchedeyLR** [comment]
Did they add the faulty ones for the 1.1.0 release?. If any person download that version by error or because a new issue is in the new version, what would happen?

**Comment by beantaco** [comment]
No, there were no checksums for [1.1.0](https://github.com/loki-project/session-android/releases/tag/1.1.0) at all. Compare that with for instance [1.2.0](https://github.com/loki-project/session-android/releases/tag/1.2.0), which shows a PGP signed message containing checksums in the release statement.

**Comment by EchedeyLR** [comment]
> No, there were no checksums for [1.1.0](https://github.com/loki-project/session-android/releases/tag/1.1.0) at all. Compare that with for instance [1.2.0](https://github.com/loki-project/session-android/releases/tag/1.2.0), which shows a PGP signed message containing checksums in the release statement.
> 
> If someone downloaded version 1.1.0, they may still be able to use Session but they would not be able to verify the download is not corrupted or tampered with.

If any person download that version by error or because a new issue is in the new version, what would happen?

**Comment by KeeJef** [comment]
Missing signatures have been updated, no user should still be using the 1.1.0 release

**Comment by EchedeyLR** [comment]
> Missing signatures have been updated, no user should still be using the 1.1.0 release

They should not, but as happened with Delta Chat, for example Cuban users, it is reported sometimes in the new issues as using a veeeery older version due to releases not working from a version or just faulty access.

**Comment by beantaco** [comment]
@KeeJef : Can the binary release process be changed so that no binary is ever published in the absence of a signed list of checksums? In other words, block a release from being published if any checksum is missing or if any signature/checksum verification fails.

**Comment by KeeJef** [comment]
@beantaco the signing process is intentionally done manually so a compromise of our automated build system would not result in compromised signed binaries being released. However we can look at ways to improve this

**Comment by beantaco** [comment]
> the signing process is intentionally done manually so a compromise of our automated build system would not result in compromised signed binaries being released.

I understand the necessity to manually calculate checksums and manually sign them, due to the risk of compromise if these steps were automated. My proposal is a check that blocks release of binaries if any checksum or signature is missing or invalid. Thanks for looking into it!

**Comment by beantaco** [comment]
There are no checksums for version [1.2.5](https://github.com/loki-project/session-android/releases/tag/1.2.5), so nobody can verify them before installing.

**Comment by KeeJef** [comment]
Signatures have been added, ill talk to Niels about informing me before binaries are released so i can sign them when they are in draft

**Comment by beantaco** [comment]
That was a quick response. Thank you!
