### ISSUE TITLE
Possible to pair two devices

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-android#181]
**Describe the bug**

With Android as primary device, if I repeat the pairing device process directly after accepting a pairing request, I can pair an other device.

**To reproduce**

On an Android (primary) device, start the pairing device process with a secondary device. After accepting the pairing request, it is possible to quickly click on the ‘Link a device’ button again and start the pairing process with a second device.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Nexus 5
 - OS: Android 10.0
 - Version of Session or latest commit hash: 2af186a8bf0e23c1a69c19047f9b9487f430aa47

**Additional context**

**Comment by Mikunj** [comment]
This is actually solved as a ux fix in #115. @nielsandriesse
