### ISSUE TITLE
Text sent together with an attachment is not showed at all

### ISSUE THREAD

**Issue by EchedeyLR** [loki-project/session-android#183]
**Describe the bug**

When a attachment, such as an image, is sent, you can add text with it. After certain number of characters, the text is not showed at all once you sent it. However, this seems to be an issue only displaying the text because if I reply to that message with an attachment, in which the attachment is decreased to the right of the reply reference, the text seems to be displayed correctly.

**To reproduce**

Send an image, for example, and add a full sentence.

**Screenshots or logs**

![Screenshot_20200429-175915](https://user-images.githubusercontent.com/56733813/80633256-62555e00-8a50-11ea-92e1-09b85defce8d.png)

**Smartphone (please complete the following information):**

 - Device: BQ Aquaris U Plus
 - OS: LineageOS 14.1 from microG
 - Version of Loki Messenger: 1.1.0.495

**Additional context**

Only tested with a gif from built-in Giphy and images but I think it could affect to other types.

**Comment by KeeJef** [comment]
This is fixed in the latest version
