### ISSUE TITLE
Mute icon dissapear inside groups

### ISSUE THREAD

**Issue by EchedeyLR** [loki-project/session-android#188]
**Describe the bug**

If I mute a group, 1-2 seconds after entering again to see messages inside, the mute icon on top, near to the group title, dissapear leaving the text about the muting indentated wrongly. The indentation in the text about muting is fixed to the left after opening the keyboard and maintained later until I join in the group again to see the issue.

**To reproduce**

Enter in a group, mute it, go to main Session panel, and enter in the group again to see messages.

**Screenshots or logs**

![image-2149780816](https://user-images.githubusercontent.com/56733813/80715064-bcf0c780-8aed-11ea-83ad-4800f8002f3f.png)

![image-4223286640](https://user-images.githubusercontent.com/56733813/80715089-c417d580-8aed-11ea-83fc-3694a7e6da03.png)

![image-3525244107](https://user-images.githubusercontent.com/56733813/80715103-c9752000-8aed-11ea-869b-52b070dfa36e.png)

![image-3696495006](https://user-images.githubusercontent.com/56733813/80715112-ced26a80-8aed-11ea-8b4f-cb26e9d80983.png)

**Smartphone (please complete the following information):**

 - Device: BQ Aquaris U Plus
 - OS: LineageOS 14.1 from microG
 - Version of Loki Messenger: 1.1.0.495

**Additional context**

Tested with Open Groups only.

**Comment by Brice-W** [comment]
This has been fixed
