### ISSUE TITLE
Sharing panel in full screen by default

### ISSUE THREAD

**Issue by EchedeyLR** [loki-project/session-android#190]
**Describe the bug**

Trying to share anything by the sharing panel, finish in the panel being opened in full screen.

However, opening the keyboard seems to solve the issue to the normal size.

**To reproduce**

Enter into any kind of chat, open the sharing panel.

Then, open the keyboard and try again to open the sharing panel.

**Screenshots or logs**

![image-1547680164](https://user-images.githubusercontent.com/56733813/80914957-ece6d780-8d46-11ea-8c81-38c6f2ecef57.gif)

**Smartphone (please complete the following information):**

 - Device: BQ Aquaris U Plus
 - OS: LineageOS 14.1 from microG
 - Version of Loki Messenger: 1.1.0.495

**Additional context**

Not tested with closed groups.

**Comment by KeeJef** [comment]
This is fixed in the latest version
