### ISSUE TITLE
session-android-service: Compile fail

### ISSUE THREAD

**Issue by whitestone8214** [loki-project/session-android#196]
Hi.
Issue for session-android-service(https://github.com/loki-project/session-android-service), but session-android-service has no Issues tab, so I had to write here.

session-android-service is required to build Session for Android, But it fails to build.

What I launched (Since it is code error, so anyone can meet this error just with following command on top directory of source tree):

> ANDROID_HOME=/media/yukari/android-app-development ANDROID_NDK_HOME=/media/yukari/android-app-development/ndk gradle build -S -g /media/yukari/android-app-development/gradle-cache

What fails:

> /media/yukari/android-app-development/libraries/session-android-service/1.1.0/java/src/main/java/org/whispersystems/libsignal/ecc/Curve.java:24: error: method generateKeyPair in class Curve25519 cannot be applied to given types;
>     Curve25519KeyPair keyPair = Curve25519.getInstance(BEST).generateKeyPair(seed);
>                                                             ^
>   required: no arguments
>   found: byte[]
>   reason: actual and formal argument lists differ in length

May I ask you to fix this bug?
Thank you.

P.S. Attached file is a full log.
[error.txt](https://github.com/loki-project/session-android/files/4607711/error.txt)

**Comment by Haafingar** [comment]
See #201
