### ISSUE TITLE
feature, nice to have, comments

### ISSUE THREAD

**Issue by realjench** [loki-project/session-android#199]
1) for not geeky, please in the installation, let know some really important security settings ( fingertip, block screen shot)

2) on Android not easy to find the seeds

3)cool feature, multiple account swapping

4)cloudflare and Google not good, maybe decentralize push notif or synch pull with fewer battery usage.

5) nice to have, add a list of bridge, give the possibilities to choose a country exit point

6)And for the paranoid android, let change the number of hops or add i2p to tor

On mobile device, add the ttl, might be so useful 

Five eyes 6,7,8😉

Thanks a lot

**Comment by realjench** [comment]
Knock knock, anybody home?

**Comment by KeeJef** [comment]
1. Not sure what you mean by this 
2. You should be prompted to backup your seed on installation, what do you mean by hard to find? 
3. Thats planned but wont happen before other improvements are made 
4. Push notifications from Firebase are optional, not sure if we use cloudflare anywhere other than the website? 
5. We dont have bridges yet
6. Session uses its own onion routing later, changing hops doesn't seem overly useful, best to make most traffic uniform 
7. You mean an option to change your TTL?
