### ISSUE TITLE
Can`t create or restore Session account [bug]

### ISSUE THREAD

**Issue by Nick-1231** [loki-project/session-android#222]
**Describe the bug**
Can not create or restore Session account because I can`t scroll down to press "OK" button.

**Steps to reproduce the bug**
Try to create or restore Session account.

**Screenshots**

[![](http://f26.ifotki.info/org/ca829615c81a9bec87ee51be429adf320503b4374190220.png)](http://f26.ifotki.info/org/ae4df2c665ed8d4d572f4f2bda2e264d0503b4374190220.png)

**Smartphone (please complete the following information):**
 - OS: Android 9
 - Session v1.2.1 (latest)

**Additional context**
I hope, that this **BIG LITTLE BUG** will be solved in next version of Session update...

**Comment by nielsandriesse** [comment]
This has been fixed and will be shipped with the next update
