### ISSUE TITLE
UX/ UI Request 

### ISSUE THREAD

**Issue by OlderNews** [loki-project/session-android#226]
**Describe the bug**

**To reproduce**

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy S8]
 - OS: [e.g. Android Pie]
 - Version of Session or latest commit hash

**Additional context**

**Comment by KeeJef** [comment]
this issue is empty so im closing
