### ISSUE TITLE
ClassyShark3xodus returned strange result of Firebase Anaytics after scanning session app

### ISSUE THREAD

**Issue by subsys-R9boq8** [loki-project/session-android#231]
ClassyShark3xodus returned one class of Firebase Analytics after scanning session app downloaded from the release page.

Does this necessarily means session-android contains Google Firebase Analytics? Or can you clarify?
It doesn't sounds like you enabled Firebase Analytics to me, but it shouldn't have returned any results **if you're only using FCM in the first place** (just like Signal) There's discussion beginning in the privacytools.io github issue already.

https://github.com/privacytools/privacytools.io/issues/1678#issuecomment-643201921

**Comment by KeeJef** [comment]
We have never actually used Firebase analytics in a production version of the application, these static code analyzers seemed to be picking up the inclusion of the Google Firebase library (Used for FCM) as and flagging that, but as of last week we have excluded those parts that were getting flagged by Exodus and now we are passing https://reports.exodus-privacy.eu.org/en/reports/network.loki.messenger/latest/.

You can see the PR here https://github.com/loki-project/session-android/pull/219

Regarding FCM for push it is only ever used if the user opts in to use it, you can use Session Google free if you just use background notifications.

**Comment by subsys-R9boq8** [comment]
Thanks for the explanation! Downloaded the latest release and Exodus returned no trackers now.
