### ISSUE TITLE
Message under images gets cut off

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-android#233]
**Describe the bug**

When I send an image or a photo with a text message, the text gets cut off after the first line. This mostly likely to happen if there are only a couple of words on the second line. If the text is long enough, it might show more than one line, but it’s likely that the very end of the message will be cut off.

**To reproduce**

In a user conversation or a group, attach a photo to a text message. The text message has to be a couple of words longer than one line (like in the screenshot).

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.
<img width="367" alt="Screen Shot 2020-06-16 at 11 53 05 am" src="https://user-images.githubusercontent.com/62363622/84723003-fc08a880-afc7-11ea-9a34-443a10b10ab6.png">

**Smartphone (please complete the following information):**

 - Device: Nexus 5X (virtual device)
 - OS: Android R
 - Version of Session or latest commit hash f85ad3564b9e0c42a7d13b56f565564fdc6dc963

**Additional context**

**Comment by nielsandriesse** [comment]
I believe this has been fixed

**Comment by Brice-W** [comment]
There is still a scenario where this is happening:
Send an image with a message that’s long enough to be displayed on 2 lines (with only 1 or 2 words on the second line). Once the message is sent, send another message (no media this time). The text gets cut off on both devices (both Android).

![Screen Shot 2020-08-10 at 2 23 54 pm](https://user-images.githubusercontent.com/62363622/91519221-5792d300-e935-11ea-83ea-01fa0b78ab1e.png)
