### ISSUE TITLE
No link preview 

### ISSUE THREAD

**Issue by 123chuck123** [loki-project/session-android#235]
**Describe the bug**

When I share a youtube link no link preview is shown. The option is activated.
Same with reddit and instagram.
But on the desktop app it works just fine.

**To reproduce**

Share youtube link or instagram link or reddit link.

**Smartphone (please complete the following information):**

 - Device: Xiaomi MI 9T Pro
 - OS: Android 10 Custom Rom: Evolution X
 - Version of Session or latest commit hash: 1.2.3 latest version from play store

**Comment by KeeJef** [comment]
Link previews should be working well now for select sites (youtube, imgur, and a few others) you just need to turn the setting on.
