### ISSUE TITLE
Failed messages on multi device.

### ISSUE THREAD

**Issue by OlderNews** [loki-project/session-android#241]
Android to IOS messaging with PC multi-device enabled

Sending message from Android to IOS. Message Fail message icon appears, click to resend. Re sent 3 times, still didn't show up. I then opened up desktop and 3 messages went through on the desktop but Mobile still says message failed. 

2 Images attached, one with the Red ! is the view from Mobile and the one with 3 messages repeated is the desktop View. 

![Screenshot_20200624-153123_Session](https://user-images.githubusercontent.com/42824519/85504938-72448500-b630-11ea-9e45-8f82aecaa376.jpg)
![20200624_153149](https://user-images.githubusercontent.com/42824519/85504940-74a6df00-b630-11ea-8603-4f2a256a26f5.jpg)

**Comment by KeeJef** [comment]
Multi device removed for now, so closing this
