### ISSUE TITLE
Session Android causing extreme battery usage

### ISSUE THREAD

**Issue by pjv** [loki-project/session-android#249]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Started trialing Session for a potential move away from Signal and with Session running in the background on my Moto x4, Android version 9, saw extreme battery drain. I have Session set to use FCM push notifications. There was no actual Session activity other than a couple of test "Note to Self" message between Session on my desktop and Session on my phone.

### Steps to reproduce
- Use Session on my Android phone.

**Actual result:**

Fast battery drain.

**Expected result:**

Normal (comparable to Signal Android) battery usage.

**Device:** Motorola Moto x4

**Android version:** 9.0.0 Build number PPWS29.69-39-6-9

**Session version:** 1.2.4

**Comment by KeeJef** [comment]
Is battery usage also high with FCM?

**Comment by pjv** [comment]
![2020-07-06 at 4 47 AM](https://user-images.githubusercontent.com/327716/86580112-e1c94700-bf43-11ea-9252-d06a5b63af7c.jpg)

**Comment by pjv** [comment]
I can add that the battery drain only occurs when the app's UI is active in the foreground or background on the phone. If I go into the background app management view and swipe up on session to unload it, then the battery drain stops even though whatever background process that is still alive listening for push notifications is still running (verified by successfully receiving push notifications for session messages on the phone).

**Comment by pjv** [comment]
And as an aside, I really hope that you guys can work out the kinks in Session. From what I've read so far, you've made all the right big picture design changes to Signal that I would want and it is absolutely cool that I was able to exchange e2e encrypted text messages with perfect forward secrecy and IP obfuscation with just a couple of public-private keypairs on either end. Super cool.

**Comment by pjv** [comment]
As far as I can tell, v. 1.3.0 is no longer draining my battery. Nice work.
