### ISSUE TITLE
Crash when adding emoji to message with photo.

### ISSUE THREAD

**Issue by gitmaker032** [loki-project/session-android#257]
**To reproduce**

1. Attach any picture to the empty message.
2. In the text field, try to add an emoji (by clicking on the button with a smiley).
3. The application crashes or the screen with the addition of a photos crashes.

**Screenshots**

![Screenshot_2020-07-14-20-17-46-806_network.loki.messenger~4.jpg](https://user-images.githubusercontent.com/67278783/87456591-d47d1e00-c60f-11ea-9e72-8f235edf3a1d.jpg)

**Smartphone:**

 - Device: Xiaomi Redmi Note 8 Pro
 - OS: Android 10, Miui 11
 - Version of Session: 1.2.5

**Comment by nielsandriesse** [comment]
This has been fixed :)

**Comment by gitmaker032** [comment]
> This has been fixed :)

Thanks :)
