### ISSUE TITLE
Image + Text = Cut off text on Mobile only

### ISSUE THREAD

**Issue by OlderNews** [loki-project/session-android#264]
Using Android latest version 1.3.0

I took a screenshot and added the phrase from my mobile: 
 "of course it's laggy, our messages bounce around the world ahha"
- "Only the Image and Of course its laggy, our" is the only text readable on the mobile device. 

![image](https://user-images.githubusercontent.com/42824519/87889130-656e5200-ca73-11ea-9fce-a646aad8ece3.png)

On Mobile, I can not expand the text and read the message no matter what I do, but on Desktop the whole message pops up. 

**To reproduce**
Send a long message+ image together to another device. Only 6 or so words can be read from the mobile device. 

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung note 9 ]

 - 1.3.0

**Comment by nielsandriesse** [comment]
I believe this has been fixed
