### ISSUE TITLE
JazzIcons on public chat changes every time a user sends a new message.

### ISSUE THREAD

**Issue by Mikunj** [loki-project/session-android#28]
**Note:** JazzIcons for the same user don't match on both images

![image](https://user-images.githubusercontent.com/4365065/65395316-8971f000-dddc-11e9-9ca2-70915d900028.png)
![image](https://user-images.githubusercontent.com/4365065/65395323-9bec2980-dddc-11e9-8d18-b870fd37be53.png)

**Comment by gmbnt** [comment]
I think this is due to capitalization (the hex encoded public key being capitalized by Android vs not by the back-end, iOS & desktop)

**Comment by Mikunj** [comment]
> I think this is due to capitalization (the hex encoded public key being capitalized by Android vs not by the back-end, iOS & desktop)

Hmm doesn't seem to be as i remember making everything lowercase. Might be some weird cache/cell reuse issue?
