### ISSUE TITLE
Images are not loaded or displayed in chats

### ISSUE THREAD

**Issue by gitmaker032** [loki-project/session-android#289]
After some time after receiving a message with an image, information about the impossibility of downloading the message is displayed. A gray square is displayed instead of an image. Relevant for all chats and for any images. Tested on multiple devices.

![200102200144_1912_bug](https://user-images.githubusercontent.com/67278783/90887984-12632400-e3be-11ea-88bd-514f8b2876c6.jpg)

OS: Android 10
Session version: 1.4.0 - 1.4.3

**Comment by nielsandriesse** [comment]
This will be fixed with the upcoming 1.4.5 release
