### ISSUE TITLE
Message highlighting and reply not working correctly

### ISSUE THREAD

**Issue by fleapower** [loki-project/session-android#294]
**Describe the bug**

When selecting a message which to reply, I need to slide my finger a bit to highlight the message.  If the message is a reply to another message, highlighting doesn't work at all.  Additionally, the reply and session key are absent from the menu in the top right.

**To reproduce**

Press and hold a message in a chat (no response).  Slide finger slightly and message is highlighted.  Reply and session key icons are missing.

**Screenshots or logs**

![image](https://user-images.githubusercontent.com/16828200/90926482-32e0ad80-e3c1-11ea-8c79-2e7daab39529.png)

**Smartphone (please complete the following information):**

 - Device: Nokia 6.1 2018
 - OS: Android 10
 - Version of Session:  1.4.2

**Additional context**

1)  To get a message with a reply highlighted, first select a non-reply message, then select the "reply", then deselect the non-reply message.
2)  Once a message is highlighted, the reply and session ID icons can be restored by either clicking in the "Message" box at the bottom of the screen; leaving the conversation and then immediately going back in; or switching to another app and then back to Session.
3)  Once the reply functionality is restored, it seems to work until going into another chat.

**Comment by nielsandriesse** [comment]
We're aware of this bug! It's on our to do list :)

**Comment by Brice-W** [comment]
This has been fixed
