### ISSUE TITLE
Add logout button in settings menu.

### ISSUE THREAD

**Issue by Sonofotis** [loki-project/session-android#3]
I wanted to generate a new key for testing however there is no logout button.

**Comment by KeeJef** [comment]
Not sure this really makes sense, theres nothing to really login to, i think this could be confusing

**Comment by Sonofotis** [comment]
Clear data button was added which does exactly what a log out button would do.

The clear data button isn't really clear as to what it does though.

It says "This will permanently delete your messages, session and contacts", but what it is really doing is removing your key from the application.

**Comment by KeeJef** [comment]
it also deletes your messages and other stored data
