### ISSUE TITLE
System Back button doesn't work in chat view

### ISSUE THREAD

**Issue by CyberFoxHax** [loki-project/session-android#308]
System Back button does not work inside a normal convos and group convos. Clicking the button has no effect whatsoever.
This only happens on my device not on my friends device.

Device info:
OnePlus 7 (GM1910) running HydrogenOS 10.0.3.GM21
Session v1.4.2

**Comment by nielsandriesse** [comment]
This is on our to do list. It should be fixed soon :)

**Comment by CyberFoxHax** [comment]
thank you for your hard work. Can't wait to uninstall Signal. :)

**Comment by Brice-W** [comment]
This should be fixed with the new back button
