### ISSUE TITLE
Application Notes Access to Location Data in Android Store

### ISSUE THREAD

**Issue by GraftSpy** [loki-project/session-android#32]
I believe that a lingering feature from Signal allowing users to share their location has been left in the application--when installing the application it is noted (in the Google Playstore) that the app requests/requires access to location data. 

loki-messenger-android/src/org/thoughtcrime/securesms/components/location/

Note that I messed around with the application and I could not get it to request my location -- I don't think it is actually accessing location data.

**Comment by yidakee** [comment]
I actually suggested on Discord a while ago, this could be a killer feature for example, whistleblowers and journalists to meet. Send GPS coordinates, or drop a package take a pic with GPS, and send - stuff like that.

**Comment by GraftSpy** [comment]
I thought about that -- but why not just record GPS coordinates and paste them as text?  I suppose it's more convenient/faster to do it all within a single application, but I just wonder if integrating google maps somehow compromises security/anonymity.

**Comment by yidakee** [comment]
@GraftSpy - Good point. Just food for thought.

**Comment by nielsandriesse** [comment]
We've removed this for now. In the future we might add it back depending on where we want to take the app.
