### ISSUE TITLE
Send message fail

### ISSUE THREAD

**Issue by synthgab** [loki-project/session-android#377]
**Describe the bug**
I cannot send any message, except for one, after a fresh start of the application (plane mode, force close, clear cache, wait 2 minutes, then connect and launch session).

Same behavior (and "workaround") when trying to join an open group (the session feedback or chat)

I also find similar closed issues here, I think I have a recent version and still face this problem.

**To reproduce**
Launch session and try to send a message, any kind...

**Screenshots or logs**
Nothing more than the red exclamation mark telling that message send failed

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S9
 - OS: Android 10, Samsung stock
 - Version of Session: 1.6.3 (1185)

**Additional context**
I even tried to start from scratch (purge data and create a new key/seed): same issue

[Edit] fixed a few typos

**Comment by feroxaquila** [comment]
I have similar issues can't send messages. Keeps giving "Send failed, tap for details". Randomly some messages are sent but most of my messages giving this error.

**Comment by synthgab** [comment]
Hello,

It seems way better after the update to latest version 1.6.4

Good job for fixing this, guys, Session begins to be ready to de advertised as usable and reliable...

Thanks !
