### ISSUE TITLE
Messages between clients don't show

### ISSUE THREAD

**Issue by Billy02357** [loki-project/session-android#391]
1. I send a message to a contact from my phone
2. I open my desktop application on my PC
3. Messages sent from the phone won't show up on the desktop app

Is this an issue or it's just not implemented? if its not implemented, it would be great to be added.

**Comment by KeeJef** [comment]
Multi device is not yet officially supported in Session, linking devices by restoring the same seed on both devices does work for incoming messages but sent messages are not synced, we will be adding official support for multi device soon
