### ISSUE TITLE
Images won't send

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/session-android#49]
**Describe the bug**
Images won't send, continuous waiting symbol. 

**Screenshots or logs**
![sketch-1575267796813](https://user-images.githubusercontent.com/29006257/69935415-b8879a80-14cc-11ea-84e1-a38e42437d7a.png)

**Smartphone (please complete the following information):**
 - Device: Xperia xz2 premium 
 - OS: Android 9
 - Version of Loki Messenger: 1.5.0

**Comment by Mikunj** [comment]
Hey, does this happen when you try send the same image to another contact?

**Comment by Lucifer1903** [comment]
No, this happens when I try to send any image to another contact.

**Comment by Mikunj** [comment]
Okay i'll start looking into this, could you test one small thing for me?
1. Go into a public chat and attach a gif and send it.
2. Go into a private chat and attach the same gif and send it.
Does it send successfully to the public chat?

**Comment by Lucifer1903** [comment]
Okay, I've tried sending photo in both public and private chat, they both sent successfully. How the previous images is still training to send. I've tried restarting the phone which didn't help and I've tried deleting the image that's still trying to send from loki messenger but it won't delete.

**Comment by Lucifer1903** [comment]
I tried sending a gif in both public and private chat, it sends in private chat but won't send in public chat.
![Screenshot_20191202-061824](https://user-images.githubusercontent.com/29006257/69935068-b96bfc80-14cb-11ea-981b-83dbd279185a.png)

**Comment by Lucifer1903** [comment]
This is still stuck trying to send and can't be deleted.
![Screenshot_20191202-062036](https://user-images.githubusercontent.com/29006257/69935150-ee784f00-14cb-11ea-8cd9-fed29dedf3c6.png)

**Comment by Lucifer1903** [comment]
This is still stuck trying to send and can't be deleted.
![sketch-1575267819009](https://user-images.githubusercontent.com/29006257/69935352-7f4f2a80-14cc-11ea-996a-3a3a82122556.png)
