### ISSUE TITLE
Insecure SMS

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/session-android#56]
**Describe the bug**
Useless button left over from Signal. 

**To reproduce**
Open a person to person chat, type anything, hold down on the send button. It will display 2 options to send, one being SMS. 

**Screenshots or logs**
![Screenshot_20191215-011843](https://user-images.githubusercontent.com/29006257/70856714-8d904400-1ed9-11ea-8f83-2ded0c43782f.png)

**Smartphone (please complete the following information):**
 - Device: Xperia xz2 premium 
 - OS: Android 9 
 - Version 1.5.2 of Loki Messenger

**Comment by Mikunj** [comment]
Good catch, i'll get a fix in soon :)

**Comment by wuniversales** [comment]
And it is not better to encrypt the sms.
Do something like silence ...
https://silence.im/
Allow to send messages via SMS, but encrypted
