### ISSUE TITLE
User eXperience: Better Identicon for Users

### ISSUE THREAD

**Issue by patoshii** [loki-project/session-android#7]
Currently the identicons being used on the messenger is very generic. A better user experience approach is to implement a more meaningful avatar for users. See: https://uxdesign.cc/design-avatars-that-make-sense-and-be-more-inclusive-in-the-process-d4dd6a486ea6

I'd recommend: https://github.com/luciorubeens/pictogrify

Big list: https://drhus.github.io/awesome-identicons/

**Comment by Lucifer1903** [comment]
It would be good if you could select which identicon format you want contacts to see. Maybe this should be moved from here (loki-messenger-android) to loki-messenger?

**Comment by KeeJef** [comment]
We've moved to a different identicon design which fits better with the visual theme of the application
