### ISSUE TITLE
Display username in notifications instead of public keys 

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/session-android#74]
**Describe the bug**
Public keys are displayed in notifications, it would be better to display usernames as keys are too long and not easy to recognise. 

**To reproduce**
Receive a message notification. 

**Screenshots or logs**
![Screenshot_20200205-090906](https://user-images.githubusercontent.com/29006257/73828015-75151980-47f8-11ea-8c9b-e3350fe947a4.png)

**Smartphone (please complete the following information):**
 - Device: Xperia xz2 premium 
 - OS: Android 10
 - Version of Session Messenger: 1.0.0

**Comment by gmbnt** [comment]
This has been fixed.
