### ISSUE TITLE
Clicking on message doesn't mark the messages as read 

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/session-android#75]
**Describe the bug**
When a message notification is clicked it doesn't dissappear as it should and the loki icon on the android home screen still has a count for the message. The only way to get the app to realise that the message is read is by clicking mark read in the notification. 

**Screenshots or logs**
![Screenshot_20200205-094606](https://user-images.githubusercontent.com/29006257/73830379-84966180-47fc-11ea-8f18-46b00cffa1e6.png)
![Screenshot_20200205-094634](https://user-images.githubusercontent.com/29006257/73830408-8c560600-47fc-11ea-847f-bb7c80777d5b.png)

**Smartphone (please complete the following information):**
 - Device: Xperia xz2 premium 
 - OS: Android 10 
 - Version of Session Messenger:

**Comment by Lucifer1903** [comment]
It seems that if you look at the messages it doesn't get marked as read until someone sends a new message that you haven't seen. At that point the old messages become read and the new messages won't be marked as read until either the mark read button is clicked or you look at the message and wait for someone to send a new message.

**Comment by Lucifer1903** [comment]
Session has been updated to 1.0.2 and now notifications will close if the notification is clicked, however notifications continues to display after reading the message within the Session app and the unread messages count continues to display on the app icon even after all messages have been read.
![Screenshot_20200217-191044](https://user-images.githubusercontent.com/29006257/74681566-9e03ba00-51bb-11ea-863a-4d49fc2d4e1a.png)

**Comment by nielsandriesse** [comment]
I believe this has been fixed
