### ISSUE TITLE
Enhancement: Back Button for Android 

### ISSUE THREAD

**Issue by Skelaton4** [loki-project/session-android#76]
**Describe the bug**
I think a back button would greatly help with user experience. It can be frustrating on larger phones to use the system back button.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android 10
 - Session  Messenger 1.0 
![Screenshot_20200205-220515_Session](https://user-images.githubusercontent.com/28955674/73902475-fa81e380-4863-11ea-8e53-281606f66bed.jpg)

**Additional context**

**Comment by pjv** [comment]
@Skelaton4 why did you close this issue?

**Comment by Skelaton4** [comment]
Happy to Re-Open as I do think this would be a nice feature.

**Comment by pjv** [comment]
It's pretty confusing without it. What seems strange is that it exists in Signal android so someone must have consciously removed it from the UI for some reason.

**Comment by KeeJef** [comment]
This will be added in the next release
