### ISSUE TITLE
Session notifications are not dissapearing after open

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-android#84]
**Describe the bug**
“Session notifications are not dissapearing after open. Can you report the notifications bug to the team? My friends are experiencing it too”

Reporting for use on discord in messenger help

**To reproduce**

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S8]
 - OS: [e.g. Android Pie]
 - Version of Loki Messenger or latest commit hash

Android 8 and 9. Xiaomi and OnePlus phones

**Additional context**

**Comment by Lucifer1903** [comment]
I already made a bug report for this https://github.com/loki-project/session-android/issues/75
