### ISSUE TITLE
Photos not sending 

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/session-android#85]
**Describe the bug**
Photos not sending 

**To reproduce**
Send a photo, not sure why it isn't sending but it might be because of the phone model or android version. 

**Screenshots or logs**
![signal-2020-02-09-051335](https://user-images.githubusercontent.com/29006257/74097170-df7fcf80-4b00-11ea-99c3-f8ef7d6991e3.png)

**Smartphone (please complete the following information):**
 - Device: Xperia Z5
 - OS: Android 7.1.1
 - Version of Session Messenger: 1.0.1

**Comment by EchedeyLR** [comment]
Could you try holding the image and retry in the options?

I have had the same experience with some audio files and pictures even being light but after retry, they were sent.

**Comment by Lucifer1903** [comment]
I fully remember but I think I tried that and it didn't work. Got a new phone now but if it happens again I'll make sure I try that.

**Comment by quantumpacket** [comment]
F-droid

**Comment by Domino117** [comment]
Same exact problem here.  Unfortunately I don't have the resources to go buy a new phone.  Resend option does not resolve the problem.  I can receive photos from the other party.  Tried to re-establish secure connection, killed running process and cached process, and cleared storage cache.  I use Nova Launcher but also tried on stock.  I'm otherwise really impressed with the app so far.

• ZTE ZMax Pro
• Android OS 6.0.1
• Session Version 1.0.4

**Comment by Lucifer1903** [comment]
@EchedeyLR on what decide and OS are you experiencing these issues?

**Comment by EchedeyLR** [comment]
@Lucifer1903 sorry for the delay:

- Device: BQ Aquaris U Plus
- OS: LineageOS 14.1 from microG
- Version of Loki Messenger: 1.0.4 (not tested in 1.0.5 but expected working)
- File size: a maximum of 6 MB

**Comment by Domino117** [comment]
No difference for me in the latest release of 1.0.5.  Didn't expect anything as it wasn't listed in the release notes.

**Comment by nielsandriesse** [comment]
Should be fixed

**Comment by EchedeyLR** [comment]
Could other people confirm if the issue is solved for real?

**Comment by Domino117** [comment]
Looks to be working well for me.  Thank you.

**Comment by EchedeyLR** [comment]
Perfect.
