### ISSUE TITLE
Screen Stuck Device Pairing Android with OSX

### ISSUE THREAD

**Issue by ChrisKoos** [loki-project/session-android#89]
**Describe the bug**

Android Screen stucks withing pairing.

**To reproduce**
I want to report a bug that is happening on my Android phone. 

I tried to pair the device as follows:

Opened the Session messenger app on my Android phone
Clicked on "Link to an existing account."
Opened the Session Desktop App
Clicked on Devices "Link New Device"
Scanned the bar code with my Android phone
Clicked on Filter receiving requests 
Allowed pairing the device
Done

The device is paired on my Macbook, as you can see in the screenshot.

However, the screen on my Android device is still stuck, as you can see in the attached image.

**Screenshots or logs**

[Android Stuck](https://www.imageupload.net/image/JQIPp)
[Device Paired Desktop works](https://www.imageupload.net/image/JQbdk)

**Smartphone (please complete the following information):**
 - Device: Motorola G5S Plus (XT1805)
 - OS: Android 8.1.0
 - Version of Loki Messenger 1.0.1

**Additional context**

**Comment by gmbnt** [comment]
This has been fixed. Will be rolled out with the 1.0.2 release.
