### ISSUE TITLE
Your app for fdroid

### ISSUE THREAD

**Issue by theScrabi** [loki-project/session-android#92]
Hello,

have you thought about publishing your App on fdroid.org? It is a platform of purely open source apps which is operated like a Linux repository. It's much loved by the comunity and well supported.

**Comment by theScrabi** [comment]
However your app may be hard to build for fdroid as it uses
1. [binary blobs](https://github.com/loki-project/session-android/tree/master/libs)
2. [play services](https://github.com/loki-project/session-android/blob/324bf35e83d4ca0ac18712d451d8cf2b5ec9cd31/build.gradle#L100)

**Comment by zecamigo** [comment]
Thanks for doing this. Hope you can make it a truly free app soon.
