### ISSUE TITLE
Restore secure session open a new unusable chat

### ISSUE THREAD

**Issue by EchedeyLR** [loki-project/session-android#98]
**Describe the bug**
Restore secure session open a new unusable chat in the other recipient of a private conversation where that person can send messages but where the new ones from me are being sent to the old chat. The new chat cannot be deleted to.

**To reproduce**
I tried to restore the secure session and test again replies without a successful result but my friend and I saw a new issue.

I was the person who restore the secure session and a new chat appeared in my friend's client empty showing that the session was restored. 

The problem is that, knowing there are two chats now in the mobile, only the old one can be used because from the new one, that person can send messages but every message sent by me is received in the old chat. 

This new chat cannot be deleted too.

**Screenshots or logs**

Friend's session showing the two chats:
![Wire 2020-02-15 at 10_10 AM](https://user-images.githubusercontent.com/56733813/74586145-90dca480-4fdc-11ea-96d1-0cc21d79f828.jpeg)

My conversation with that person sending messages in response to the messages of the new created chat:
![Wire 2020-02-15 at 10_10 AM](https://user-images.githubusercontent.com/56733813/74586147-9934df80-4fdc-11ea-95b3-2ce89ac98f64.png)

How the new created chat appears for that person even when I was sending new messages:
![Wire 2020-02-15 at 10_10 AM_1](https://user-images.githubusercontent.com/56733813/74586149-9b973980-4fdc-11ea-832e-b10d7ed75876.jpeg)

*There is a faulty picture of the new messages from myself being showed in the old chat in my friend's Session.*

**Smartphone (please complete the following information):**
 - Device: BQ Aquaris U Plus (me), BQ Aquaris U2 (my friend)
 - OS: LineageOS 14.1 from microG (me), Android 8.1.0 from stock (my friend)
 - Version of Loki Messenger: 1.0.1.355 for both.

**Additional context**
This happened after what happened in https://github.com/loki-project/session-android/issues/97.

**Comment by nielsandriesse** [comment]
Session reset should now work correctly

**Comment by EchedeyLR** [comment]
I would leave the issue opened until is confirmed by more people as I cannot test future releases anymore by now.
