### ISSUE TITLE
Sometimes camera and microphone icons are not showed

### ISSUE THREAD

**Issue by EchedeyLR** [loki-project/session-android#99]
**Describe the bug**
Sometimes opening a already created chat neither camera nor microphone icons are showed and that make impossible, at least, record and send an audio.

**To reproduce**
Close the app window normally, open it again and enter in the chat with an already added contact.

A "solution" we found was to write a bit or just an space, delete it and then icons are showed again.

**Screenshots or logs**

Chat opened after opening Session without the icons:
![74604686-2c8f1300-50b8-11ea-9f6b-5ea6e8c6cd34](https://user-images.githubusercontent.com/56733813/80684810-2953d280-8abe-11ea-8a20-9886fb441dbb.png)

I write an space to delete it after it:
![74604696-42043d00-50b8-11ea-8f8d-ce0fc5e40e06](https://user-images.githubusercontent.com/56733813/80684841-32dd3a80-8abe-11ea-8022-b3c89e3d69b1.png)

I delete the space and icons are showed again:
![74604702-4d576880-50b8-11ea-86b1-3f5600896e54](https://user-images.githubusercontent.com/56733813/80684867-3ffa2980-8abe-11ea-80cc-74277c231ea8.png)

**Smartphone (please complete the following information):**

 - Device: BQ Aquaris U Plus (me), BQ Aquaris U2 (my friend)
 - OS: LineageOS 14.1 from microG (me), Android 8.1.0 from stock (my friend)
 - Version of Loki Messenger: 1.0.1.355 for both.

**Additional context**
Nothing by now.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
This still happens to my with version 1.0.5, I'm using some android 5.1 version that comes with a Samsung Galaxy something.

**Comment by EchedeyLR** [comment]
Any update about solving this? I can confirm the issue yet.

**Comment by cristianovitorino** [comment]
+1

Same problem.

```
Motorola Moto G4 Play
Android 7.1.1
```

**Comment by Brice-W** [comment]
This has been fixed
